# [START cloudbuild_quickstart_build]
# build docker image
steps:
- name: 'gcr.io/cloud-builders/docker'
  env:
  - 'SHORT_SHA=$SHORT_SHA'
  - 'PROJECT_ID=$PROJECT_ID'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/markdown/webserver:$SHORT_SHA', '.' ]

# push docker image
#
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'image'
  - 'push'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/markdown/webserver:$SHORT_SHA'


## - 'us-central1-docker.pkg.dev/$PROJECT_ID/python/python-image'
## [END cloudbuild_quickstart_build]

  
#create the new instance template
- name: 'gcr.io/cloud-builders/gcloud'
  id: create-instance-template  
  args:
    - compute
    - instance-templates
    - create-with-container
    - cloudbuild-instance-template-$SHORT_SHA
    #- --custom-cpu=1
    #- --custom-memory=2GB
    #- --boot-disk-size=20GB
    - --region=us-central1
    #- --subnet=mig-subnet
    #- --tags=allow-hc-and-proxy,allow-ssh
    - --container-image
    - us-central1-docker.pkg.dev/$PROJECT_ID/markdown/webserver:$SHORT_SHA

 # Update the managed instance group


- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['-c','gcloud compute instance-groups managed rolling-action start-update gcp-cb-1 --version=template=cloudbuild-instance-template-$SHORT_SHA --region=us-central1 --max-unavailable=0']
